Rails upgrade
CDRH/api pull request #138
Opened 2022-11-30 18:19 UTC by wkdewey

Upgrade to Rails 6 and Ruby 3

2024-12-20 23:16 UTC, techgique requested changes

2024-12-20 23:16 UTC, techgique commented on Gemfile
> +gem 'net-smtp'
This looks like another Rails dependency being duplicated in our Gemfile.

2024-12-20 23:16 UTC, techgique commented on CHANGELOG.md
> +- Add nested facets as described above, if desired
This part probably should point out `config/initializers/config.rb` needs the facet code we discussed in https://github.com/CDRH/prairie_forestry/pull/124 and https://github.com/CDRH/teaa/pull/110

2025-01-02 20:33 UTC, wkdewey commented on Gemfile
> +gem 'net-smtp'
```
rails s
You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
/Users/willdewey/.rvm/gems/ruby-3.1.6@api-v2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- net/smtp (LoadError)
```
I probably need to look at the gemfile more closely, bootsnap may be outdated, which makes me wonder if there is more of the Gemfile that could be updated if I compare it with a sample Rails app.

2025-01-14 23:53 UTC, techgique approved these changes

2025-01-14 23:54 UTC, merged