Local testing
CDRH/api pull request #146
Opened 2024-08-20 21:52 UTC by wkdewey

contains all the work I've been doing on the API (see #128 which this supercedes)

2025-12-20 01:50 UTC, techgique requested changes
Noting what I found before I work on the code to make revisions.

2025-12-20 01:50 UTC, techgique commented on CHANGELOG.md
> +### Migration
Migration section here is duplicated.

2025-12-20 01:50 UTC, techgique commented on .ruby-version
> +ruby-3.1.6
I'll bump this up to 3.1.7 to match all other recent releases.

2025-12-20 01:50 UTC, techgique commented on CHANGELOG.md
> +- "net-smtp" gem
What was this gem added for? Don't think we're doing anything with email in the API. If I don't see anything using this I'll test removing it.

2025-12-20 01:50 UTC, techgique commented on CHANGELOG.md
> +to the secrets file and then close the window to save. Do not commit `config/master.key` (it should be in `gitignore`)
This isn't going to display well after rendered by Markdown as the code snippet in the middle will result in the text following it just printed as a regular paragraph of text. I'll reformat this.

2025-12-20 01:50 UTC, techgique commented on Gemfile
> +gem 'net-smtp'
Oh, maybe this was added when copying from a default new Rails app? But I don't think I've seen this gem added to any others recently. As mentioned above, I'll look to see if there is any use, otherwise I'll remove it.

2025-12-20 01:50 UTC, techgique commented on Gemfile.lock
> +  x86_64-darwin-22
I think the macOS platforms being added to the platform list here caused us grief on the servers or across dev team members' workstations, so I'll probably remove these too after comparing with some other Rails app repos.

2025-12-20 01:50 UTC, techgique commented on app/services/search_item_req.rb
> +          #make sure sort is on the acutal count of documents
Typo in the comment. I'll fix this.

2025-12-20 01:50 UTC, techgique commented on app/services/search_item_req.rb
> +        end
I think this can be merged with the `if nested` further down as there isn't any alternative use of a `path` variable.

2025-12-20 01:50 UTC, techgique commented on app/services/search_item_req.rb
> +        end
Same as above, this can be merged with the `if nested` below.

2025-12-20 01:50 UTC, techgique commented on app/services/search_item_res.rb
> +        return key
Unnecessary uses of `return` here, as all final lines in the control flow here are the last code for the method. I'll remove them.

2025-12-20 01:50 UTC, techgique commented on app/services/search_item_res.rb
> +  end
This can be simplified down to just the if, elsif, and else blocks returning rather than assigning to a variable and then returning that variable.

2025-12-20 01:50 UTC, techgique commented on app/services/search_service.rb
> +    res = RestClient.post("#{@url}/#{url_ending}", json.to_json, auth_hash.merge({ "content-type" => "json" } ))
I think this can be formatted to be a little more easily read.

2025-12-20 01:50 UTC, techgique commented on app/controllers/application_controller.rb
> +    res = RestClient.post("#{ES_URI}/_search", json.to_json, auth_hash.merge({ "content-type" => "json" }))
I think this can be formatted to be a little more easily read.

2025-12-20 01:50 UTC, techgique commented on app/services/search_service.rb
> +    elsif raw_res.class == RestClient::ExceptionWithResponse
Went to look at RestClient docs to double-check this exception change (to fix an issue linked to in the commit https://github.com/CDRH/api/commit/f0b8817e5167ed960282a5f188cdacc2cab19eb4).

Re-discovered the gem hasn't been maintained for years. I made an issue about it a while ago: https://github.com/CDRH/api/issues/144 I added an additional comment related to a post I saw on the rest-client repo. But this should be a high priority for work on this repo after this release.

2025-12-20 01:50 UTC, techgique commented on config/environments/development.rb
> +  config.hosts << "whitman-dev.unl.edu"
I'll update the dev and prod environment configs with newer standardized code.

2025-12-20 01:50 UTC, techgique commented on config/initializers/new_framework_defaults_6_1.rb
> +# Once upgraded flip defaults one by one to migrate to the new default.
I'll enable these options and test the app.

2025-12-20 03:04 UTC, techgique commented on app/controllers/application_controller.rb
> +    res = RestClient.post("#{ES_URI}/_search", json.to_json, auth_hash.merge({ "content-type" => "json" }))
After looking more closely, I'm pretty sure this code isn't even being used. It's calling variables not defined anywhere (`ES_USER`, `ES_PASSWORD`, and `ES_URI`) and always calling a `raise` which would result in an exception being thrown. So I searched the code base and `post_search` isn't called from anywhere. So I think this can go.

2025-12-20 03:06 UTC, techgique commented on .ruby-version
> +ruby-3.1.6
Resolved: https://github.com/CDRH/api/pull/146/commits/d6a704ebfce774df6e4db0df2022c8c1133b3ca3

2025-12-20 03:07 UTC, techgique commented on app/controllers/application_controller.rb
> +    res = RestClient.post("#{ES_URI}/_search", json.to_json, auth_hash.merge({ "content-type" => "json" }))
Resolved: https://github.com/CDRH/api/pull/146/commits/46d3b0db4ab229f56211afd5841db4944cc5e541

2025-12-20 04:12 UTC, techgique commented on app/services/search_service.rb
> +    elsif raw_res.class == RestClient::ExceptionWithResponse
Found this doesn't handle all exceptions during testing, so added the BadRequest exception as an `||` condition here.

2025-12-20 04:26 UTC, techgique commented on app/services/search_service.rb
> +    res = RestClient.post("#{@url}/#{url_ending}", json.to_json, auth_hash.merge({ "content-type" => "json" } ))
Resolved: https://github.com/CDRH/api/pull/146/commits/b004587c12e2c66c53b164728e94b06544686d47

2025-12-20 05:13 UTC, techgique commented on CHANGELOG.md
> +- "net-smtp" gem
Resolved: https://github.com/CDRH/api/pull/146/commits/a0ed47a0d7820e328e83df4cc471ceb5975f8454

2025-12-20 05:13 UTC, techgique commented on Gemfile
> +gem 'net-smtp'
Resolved: https://github.com/CDRH/api/pull/146/commits/a0ed47a0d7820e328e83df4cc471ceb5975f8454

2025-12-20 05:14 UTC, techgique commented on Gemfile.lock
> +  x86_64-darwin-22
Resolved: https://github.com/CDRH/api/pull/146/commits/a0ed47a0d7820e328e83df4cc471ceb5975f8454

2025-12-20 05:49 UTC, techgique commented on config/initializers/new_framework_defaults_6_1.rb
> +# Once upgraded flip defaults one by one to migrate to the new default.
Resolved: https://github.com/CDRH/api/pull/146/commits/c42e264f4aed3d94026315fb1f505aa4c22d8d85

2025-12-20 06:14 UTC, techgique commented on config/environments/development.rb
> +  config.hosts << "whitman-dev.unl.edu"
Resolved: https://github.com/CDRH/api/pull/146/commits/8e6bdca86ebb18f6e671c6aa364ea66be93439c2

2025-12-20 06:17 UTC, techgique commented on app/services/search_service.rb
> +    elsif raw_res.class == RestClient::ExceptionWithResponse
Resolved: https://github.com/CDRH/api/pull/146/commits/30145d1d813b61e84c50a0f881f7bf7ad9a15037

2025-12-20 06:59 UTC, techgique commented on app/services/search_item_req.rb
> +          #make sure sort is on the acutal count of documents
Resolved: https://github.com/CDRH/api/pull/146/commits/afaf758ea806dc302ed53fcd91d93836435b3766

2025-12-20 07:00 UTC, techgique commented on app/services/search_item_req.rb
> +        end
Resolved: https://github.com/CDRH/api/pull/146/commits/afaf758ea806dc302ed53fcd91d93836435b3766

2025-12-20 07:00 UTC, techgique commented on app/services/search_item_req.rb
> +        end
Resolved: https://github.com/CDRH/api/pull/146/commits/afaf758ea806dc302ed53fcd91d93836435b3766

2025-12-20 07:15 UTC, techgique commented on app/services/search_item_res.rb
> +        return key
Resolved: https://github.com/CDRH/api/pull/146/commits/3d4842b03061d206739bc3d9fa8986afbf547f31

2025-12-20 07:16 UTC, techgique commented on app/services/search_item_res.rb
> +  end
Resolved: https://github.com/CDRH/api/pull/146/commits/3d4842b03061d206739bc3d9fa8986afbf547f31

2025-12-20 07:54 UTC, techgique commented on CHANGELOG.md
> +### Migration
Resolved: https://github.com/CDRH/api/pull/146/commits/aac16c04f961cd4fe63b13554639c05e5e9db8b8

2025-12-20 07:55 UTC, techgique commented on CHANGELOG.md
> +to the secrets file and then close the window to save. Do not commit `config/master.key` (it should be in `gitignore`)
Resolved: https://github.com/CDRH/api/pull/146/commits/aac16c04f961cd4fe63b13554639c05e5e9db8b8

2025-12-20 08:14 UTC, techgique approved these changes

2025-12-20 08:16 UTC, techgique commented
@wkdewey, please review the changes I've made to double-check I haven't made any mistakes. We might want to test this on the dev server with the dev Rails apps utilizing it as well.

The changes I made to handle Elasticsearch both with and without auth mean we can delete the `no_security_testing` branch after this is merged and deployed. Since that's what's currently deployed, note [the differences between them before I committed changes here after my review](https://github.com/CDRH/api/compare/no_security_testing...f0b8817) and [this comparison after my changes were committed](https://github.com/CDRH/api/compare/no_security_testing...local_testing). I didn't see anything that should be kept from `no_security_testing` but let me know if you spot anything.

2026-01-20 20:31 UTC, wkdewey commented
The changes you made look good, but I think some testing would be necessary.

2026-01-20 21:17 UTC, wkdewey commented
the changes on `no_security_testing` also look good

2026-05-28 16:22 UTC, techgique commented
This has been in use on dev server and sites for a couple months now. I think we're pretty confident it's reliable.

2026-05-28 16:22 UTC, merged